In [2]:
import torch

In [3]:
n = 64
device = torch.device(0)
output_points = torch.zeros((n, 3), device=device)
output_points

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0

In [4]:
output_points.shape

torch.Size([64, 3])

In [5]:
import math
r=1
horizontal_stddev=1
vertical_stddev=1
horizontal_mean=math.pi*0.5
vertical_mean=math.pi*0.5

In [6]:
theta = torch.randn((n, 1), device=device) * horizontal_stddev + horizontal_mean
phi = torch.randn((n, 1), device=device) * vertical_stddev + vertical_mean

In [7]:
output_points[:, 0:1] = r*torch.sin(phi) * torch.cos(theta)
output_points[:, 2:3] = r*torch.sin(phi) * torch.sin(theta)
output_points[:, 1:2] = r*torch.cos(phi)

In [8]:
output_points

tensor([[-0.6718,  0.5096,  0.5376],
        [-0.6757, -0.0353,  0.7363],
        [-0.7411,  0.1249,  0.6597],
        [-0.7081, -0.6511,  0.2732],
        [-0.0289,  0.9430,  0.3315],
        [-0.7224, -0.2195,  0.6557],
        [-0.4630,  0.3160,  0.8281],
        [ 0.5944, -0.7412,  0.3119],
        [-0.0935,  0.6252,  0.7748],
        [-0.2481, -0.3343,  0.9092],
        [-0.1244,  0.9640,  0.2351],
        [ 0.5235,  0.4230,  0.7396],
        [-0.8146, -0.3583, -0.4561],
        [-0.3856,  0.8539, -0.3495],
        [ 0.2993, -0.7273,  0.6177],
        [-0.5702,  0.0973,  0.8157],
        [ 0.1041, -0.3970,  0.9119],
        [ 0.9616,  0.0529, -0.2692],
        [ 0.5499, -0.2109,  0.8082],
        [-0.1382, -0.9600, -0.2435],
        [-0.2328,  0.6177,  0.7512],
        [ 0.1359,  0.1932,  0.9717],
        [-0.9587,  0.2533, -0.1290],
        [-0.3303, -0.7409, -0.5848],
        [-0.0077,  0.0532,  0.9986],
        [ 0.0290,  0.9994,  0.0174],
        [-0.1434,  0.7775,  0.6123],
 

In [15]:
import torch.nn as nn
spatial_embeddings = nn.Parameter(torch.randn(1, 32, 96, 96, 96)*0.01)
spatial_embeddings

Parameter containing:
tensor([[[[[-8.7072e-03,  3.0171e-02,  1.5796e-02,  ..., -2.9393e-03,
             5.7809e-03, -1.1942e-02],
           [-1.2406e-02,  5.4137e-03,  5.4343e-03,  ..., -4.0558e-03,
             1.2900e-02, -1.1595e-02],
           [ 3.3574e-03, -2.5962e-03, -4.6346e-03,  ..., -2.1384e-02,
             1.0455e-02,  6.6921e-03],
           ...,
           [-3.3500e-03, -8.4932e-03,  1.4508e-02,  ...,  1.4252e-03,
            -1.4685e-02, -6.2804e-03],
           [ 5.3674e-03, -1.8105e-03, -1.6038e-03,  ..., -6.6931e-03,
             9.3240e-03, -1.0773e-02],
           [ 1.4169e-03,  3.5303e-02, -4.9809e-03,  ...,  2.0268e-02,
            -1.1681e-02, -1.3962e-02]],

          [[-1.4575e-02,  5.8423e-03, -1.6416e-02,  ...,  1.4393e-02,
            -4.1546e-04, -3.2053e-03],
           [-1.6473e-03, -1.3462e-02,  3.3105e-03,  ...,  8.3262e-03,
            -7.5997e-03, -3.7582e-04],
           [-6.7903e-03,  1.9465e-02, -4.4972e-03,  ..., -1.0805e-02,
             7.813

In [33]:
import logging

# 配置日志系统，添加 FileHandler 来写入文件
log_filename = 'my_application.txt'
logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(levelname)s - %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S',
                    handlers=[logging.FileHandler(log_filename, 'a', 'utf-8')])

# 记录一条信息级别的日志
logging.info("这是一条信息级别的日志，将被写入文件")
logging.info(f"input:{input.shape}")
# 其他日志记录...


In [31]:
import logging
def logger_config(log_path,logging_name):
    '''
    配置log
    :param log_path: 输出log路径
    :param logging_name: 记录中name，可随意
    :return:
    '''
    '''
    logger是日志对象，handler是流处理器，console是控制台输出（没有console也可以，将不会在控制台输出，会在日志文件中输出）
    '''
    # 获取logger对象,取名
    logger = logging.getLogger(logging_name)
    # 输出DEBUG及以上级别的信息，针对所有输出的第一层过滤
    logger.setLevel(level=logging.DEBUG)
    # 获取文件日志句柄并设置日志级别，第二层过滤
    handler = logging.FileHandler(log_path, encoding='UTF-8')
    handler.setLevel(logging.INFO)
    # 生成并设置文件日志格式
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    # console相当于控制台输出，handler文件输出。获取流句柄并设置日志级别，第二层过滤
    console = logging.StreamHandler()
    console.setLevel(logging.DEBUG)
    # 为logger对象添加句柄
    logger.addHandler(handler)
    logger.addHandler(console)
    return logger
 
if __name__ == "__main__":
    logger = logger_config(log_path='log.txt', logging_name='据说名字长一点容易被人记住')
    logger.info("info")
    # logger.error("error")
    # logger.debug("debug")
    # logger.warning("warning")
    # print('print和logger输出是有差别的！')

info
info
info
info
info
info


In [9]:
import torch

x_dim = 32
y_dim = 32
xx_channel = torch.arange(x_dim).repeat(1, y_dim, 1)
yy_channel = torch.arange(y_dim).repeat(1, x_dim, 1).transpose(1, 2)


In [10]:
xx_channel, yy_channel

(tensor([[[ 0,  1,  2,  ..., 29, 30, 31],
          [ 0,  1,  2,  ..., 29, 30, 31],
          [ 0,  1,  2,  ..., 29, 30, 31],
          ...,
          [ 0,  1,  2,  ..., 29, 30, 31],
          [ 0,  1,  2,  ..., 29, 30, 31],
          [ 0,  1,  2,  ..., 29, 30, 31]]]),
 tensor([[[ 0,  0,  0,  ...,  0,  0,  0],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 2,  2,  2,  ...,  2,  2,  2],
          ...,
          [29, 29, 29,  ..., 29, 29, 29],
          [30, 30, 30,  ..., 30, 30, 30],
          [31, 31, 31,  ..., 31, 31, 31]]]))

In [11]:
xx_channel.shape, yy_channel.shape

(torch.Size([1, 32, 32]), torch.Size([1, 32, 32]))

In [12]:
xx_channel = xx_channel.float() / (x_dim - 1)
yy_channel = yy_channel.float() / (y_dim - 1)
xx_channel, yy_channel

(tensor([[[0.0000, 0.0323, 0.0645,  ..., 0.9355, 0.9677, 1.0000],
          [0.0000, 0.0323, 0.0645,  ..., 0.9355, 0.9677, 1.0000],
          [0.0000, 0.0323, 0.0645,  ..., 0.9355, 0.9677, 1.0000],
          ...,
          [0.0000, 0.0323, 0.0645,  ..., 0.9355, 0.9677, 1.0000],
          [0.0000, 0.0323, 0.0645,  ..., 0.9355, 0.9677, 1.0000],
          [0.0000, 0.0323, 0.0645,  ..., 0.9355, 0.9677, 1.0000]]]),
 tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0323, 0.0323, 0.0323,  ..., 0.0323, 0.0323, 0.0323],
          [0.0645, 0.0645, 0.0645,  ..., 0.0645, 0.0645, 0.0645],
          ...,
          [0.9355, 0.9355, 0.9355,  ..., 0.9355, 0.9355, 0.9355],
          [0.9677, 0.9677, 0.9677,  ..., 0.9677, 0.9677, 0.9677],
          [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]]]))

In [13]:
xx_channel = xx_channel * 2 - 1
yy_channel = yy_channel * 2 - 1
xx_channel, yy_channel

(tensor([[[-1.0000, -0.9355, -0.8710,  ...,  0.8710,  0.9355,  1.0000],
          [-1.0000, -0.9355, -0.8710,  ...,  0.8710,  0.9355,  1.0000],
          [-1.0000, -0.9355, -0.8710,  ...,  0.8710,  0.9355,  1.0000],
          ...,
          [-1.0000, -0.9355, -0.8710,  ...,  0.8710,  0.9355,  1.0000],
          [-1.0000, -0.9355, -0.8710,  ...,  0.8710,  0.9355,  1.0000],
          [-1.0000, -0.9355, -0.8710,  ...,  0.8710,  0.9355,  1.0000]]]),
 tensor([[[-1.0000, -1.0000, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
          [-0.9355, -0.9355, -0.9355,  ..., -0.9355, -0.9355, -0.9355],
          [-0.8710, -0.8710, -0.8710,  ..., -0.8710, -0.8710, -0.8710],
          ...,
          [ 0.8710,  0.8710,  0.8710,  ...,  0.8710,  0.8710,  0.8710],
          [ 0.9355,  0.9355,  0.9355,  ...,  0.9355,  0.9355,  0.9355],
          [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000]]]))

In [14]:
batch_size = 25
xx_channel = xx_channel.repeat(batch_size, 1, 1, 1).transpose(2, 3)
yy_channel = yy_channel.repeat(batch_size, 1, 1, 1).transpose(2, 3)
xx_channel, yy_channel

(tensor([[[[-1.0000, -1.0000, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
           [-0.9355, -0.9355, -0.9355,  ..., -0.9355, -0.9355, -0.9355],
           [-0.8710, -0.8710, -0.8710,  ..., -0.8710, -0.8710, -0.8710],
           ...,
           [ 0.8710,  0.8710,  0.8710,  ...,  0.8710,  0.8710,  0.8710],
           [ 0.9355,  0.9355,  0.9355,  ...,  0.9355,  0.9355,  0.9355],
           [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000]]],
 
 
         [[[-1.0000, -1.0000, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
           [-0.9355, -0.9355, -0.9355,  ..., -0.9355, -0.9355, -0.9355],
           [-0.8710, -0.8710, -0.8710,  ..., -0.8710, -0.8710, -0.8710],
           ...,
           [ 0.8710,  0.8710,  0.8710,  ...,  0.8710,  0.8710,  0.8710],
           [ 0.9355,  0.9355,  0.9355,  ...,  0.9355,  0.9355,  0.9355],
           [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000]]],
 
 
         [[[-1.0000, -1.0000, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
       

In [15]:
xx_channel.shape, yy_channel.shape

(torch.Size([25, 1, 32, 32]), torch.Size([25, 1, 32, 32]))

In [1]:
img_size_to_layer = {2:8, 4:7, 8:6, 16:5, 32:4, 64:3, 128:2, 256:1, 512:0}

In [4]:
start = img_size_to_layer[2]
start

8

In [11]:
import logging
def outlogs(message):

    # 配置日志系统，添加 FileHandler 来写入文件
    log_filename = 'test.txt'
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(levelname)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S',
                        handlers=[logging.FileHandler(log_filename, 'a', 'utf-8')])

    # 记录一条信息级别的日志
    logging.info(message)

In [12]:
outlogs("test")

In [3]:
import torch
W, H = [32, 32]
x, y = torch.meshgrid(torch.linspace(-1, 1, W,),  # (W, H)
                          torch.linspace(1, -1, H))
x, y

(tensor([[-1.0000, -1.0000, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
         [-0.9355, -0.9355, -0.9355,  ..., -0.9355, -0.9355, -0.9355],
         [-0.8710, -0.8710, -0.8710,  ..., -0.8710, -0.8710, -0.8710],
         ...,
         [ 0.8710,  0.8710,  0.8710,  ...,  0.8710,  0.8710,  0.8710],
         [ 0.9355,  0.9355,  0.9355,  ...,  0.9355,  0.9355,  0.9355],
         [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000]]),
 tensor([[ 1.0000,  0.9355,  0.8710,  ..., -0.8710, -0.9355, -1.0000],
         [ 1.0000,  0.9355,  0.8710,  ..., -0.8710, -0.9355, -1.0000],
         [ 1.0000,  0.9355,  0.8710,  ..., -0.8710, -0.9355, -1.0000],
         ...,
         [ 1.0000,  0.9355,  0.8710,  ..., -0.8710, -0.9355, -1.0000],
         [ 1.0000,  0.9355,  0.8710,  ..., -0.8710, -0.9355, -1.0000],
         [ 1.0000,  0.9355,  0.8710,  ..., -0.8710, -0.9355, -1.0000]]))

In [4]:
x.shape, y.shape

(torch.Size([32, 32]), torch.Size([32, 32]))

In [6]:
x = x.T.flatten()
y = y.T.flatten()
x, y

(tensor([-1.0000, -0.9355, -0.8710,  ...,  0.8710,  0.9355,  1.0000]),
 tensor([ 1.,  1.,  1.,  ..., -1., -1., -1.]))

In [7]:
x.shape, y.shape

(torch.Size([1024]), torch.Size([1024]))

In [20]:
import math
horizontal_stddev = 3.141592653589793
horizontal_mean = 1.5707963267948966
vertical_mean = 0.7417649320975901
vertical_stddev = 0.7417649320975901
v_stddev = 0.23611111111111113
v_mean = 0.23611111111111113
n = 3
r =1

theta = (torch.rand((n, 1)) - .5) * 2 * horizontal_stddev + horizontal_mean
v_stddev, v_mean = vertical_stddev / math.pi, vertical_mean / math.pi
v = ((torch.rand((n,1)) - .5) * 2 * v_stddev + v_mean)
v = torch.clamp(v, 1e-5, 1 - 1e-5)
phi = torch.arccos(1 - 2 * v)

phi = torch.clamp(phi, 1e-5, math.pi - 1e-5)

theta, phi

(tensor([[-1.1650],
         [ 0.4857],
         [ 4.5696]]),
 tensor([[1.4668],
         [1.0922],
         [0.4692]]))

In [21]:
output_points = torch.zeros((n, 3))
output_points

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
output_points[:, 0:1] = r*torch.sin(phi) * torch.cos(theta)
output_points[:, 2:3] = r*torch.sin(phi) * torch.sin(theta)
output_points[:, 1:2] = r*torch.cos(phi)
output_points

tensor([[ 0.3926,  0.1038, -0.9138],
        [ 0.7850,  0.4606,  0.4144],
        [-0.0643,  0.8919, -0.4476]])

In [24]:
-output_points / (torch.norm(-output_points, dim=-1, keepdim=True))

tensor([[-0.3926, -0.1038,  0.9138],
        [-0.7850, -0.4606, -0.4144],
        [ 0.0643, -0.8919,  0.4476]])

In [3]:
import torch.nn as nn
spatial_embeddings = nn.Parameter(torch.randn(1, 32, 96, 96, 96)*0.01)
spatial_embeddings

Parameter containing:
tensor([[[[[ 7.1115e-03, -5.9754e-03, -1.6532e-03,  ...,  4.8725e-03,
             3.3060e-03, -1.1705e-02],
           [ 3.2802e-05,  1.4907e-02,  3.7714e-03,  ...,  4.6412e-03,
             1.5497e-02,  8.2754e-03],
           [ 3.8742e-03, -1.5547e-02,  5.9304e-03,  ..., -1.3228e-02,
             8.9948e-03, -5.3774e-03],
           ...,
           [ 1.0560e-02,  5.5431e-03, -1.2274e-02,  ...,  9.3406e-03,
             1.3789e-02,  7.9112e-04],
           [ 4.7844e-03, -1.1935e-02, -9.9738e-04,  ..., -1.4158e-04,
             7.0029e-03, -1.2566e-03],
           [ 1.9148e-02, -1.1664e-02, -4.3361e-03,  ...,  6.7455e-03,
            -1.1548e-02,  8.6315e-04]],

          [[ 2.5640e-04,  1.1304e-02,  6.0324e-03,  ...,  1.4303e-02,
            -4.3396e-03,  8.0782e-03],
           [ 6.9591e-04, -1.0426e-02,  2.7353e-03,  ..., -2.5303e-03,
             1.2715e-02,  1.4480e-03],
           [-6.9769e-03, -1.9627e-02,  1.4970e-02,  ...,  1.2521e-02,
             1.209

In [4]:
spatial_embeddings.shape

torch.Size([1, 32, 96, 96, 96])

In [1]:
s = "ab#c"

In [2]:
s[1] = s[3]

TypeError: 'str' object does not support item assignment